kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elasticsearch
  annotations:
    volume.beta.kubernetes.io/storage-class: azurefile 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi