apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  selector:
    app: kibana
  ports:
  - name: http
    port: 80
    targetPort: 5601
    protocol: TCP
---
# Create the ingress resource
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana
  namespace: logging
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - Sorry"
spec:
  rules:
  - host: kibana-30052019a.srichards.dci-demo.azure.docker-ee.com
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana
          servicePort: 80
