apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |
    ---
    server.name: kibana
    server.port: 5601
    server.host: "0"
    elasticsearch.hosts: http://elasticsearch:9200
