apiVersion: v1
kind: ConfigMap
metadata:
  labels:
   app: fluentd
  name: fluentd-environment-es
data:
  FLUENT_ELASTICSEARCH_HOST: elasticsearch
  FLUENT_ELASTICSEARCH_PASSWORD: changeme
  FLUENT_ELASTICSEARCH_PORT: "9200"
  FLUENT_ELASTICSEARCH_SCHEME: http
  FLUENT_ELASTICSEARCH_SED_DISABLE: "true"
  FLUENT_ELASTICSEARCH_USER: elastic
  FLUENT_UID: "0"
  FLUENTD_ARGS: ="--no-supervisor -q