apiVersion: v1
kind: Service
metadata:
  labels:
    app: fluentd
  name: fluentd
spec:
  ports:
  - name: fluentd-forwarder-port
    port: 24224
    protocol: TCP
  selector:
    app: fluentd
  sessionAffinity: None
  type: ClusterIP