apiVersion: v1
kind: Service
metadata:
  name: anchore-engine-db
  labels:
    app: anchore-engine-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: anchore-engine-db
