apiVersion: v1
kind: ServiceAccount
metadata:
  name: journalbeat
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: journalbeat-read
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: journalbeat:journalbeat-role
subjects:
- kind: ServiceAccount
  name: journalbeat
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: journalbeat-read
  apiGroup: rbac.authorization.k8s.io
