apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: journalbeat
  namespace: monitoring
  labels:
    app: journalbeat
spec:
  selector:
    matchLabels:
      app: journalbeat
  template:
    metadata:
      labels:
        app: journalbeat
      annotations:
       seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: journalbeat
      securityContext:
        runAsUser: 0
      containers:
      - name: journalbeat
        image: docker.elastic.co/beats/journalbeat:7.1.1
        args:
          - "-e"
          - "-c"
          - "/usr/share/journalbeat/config/journalbeat.yaml"
        resources:
          requests:
            cpu: 50m
            memory: 250Mi
          limits:
            cpu: 50m
            memory: 250Mi
        volumeMounts:
        - name: varlog
          mountPath: '/var/log/journal'
        - name: runlog
          mountPath: '/run/systemd'
        - name: machineid
          mountPath: '/etc/machine-id'
        - name: hostname
          mountPath: '/etc/hostname'
          readOnly: true
        - name: config
          mountPath: '/usr/share/journalbeat/config'
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: '/var/log/journal'
      - name: runlog
        hostPath:
          path: '/run/systemd'
      - name: machineid
        hostPath:
          path: '/etc/machine-id'
      - name: hostname
        hostPath:
          path: '/etc/hostname'
      - name: config
        configMap:
          name: journalbeat-config
