apiVersion: v1
kind: ConfigMap
metadata:
  name: journalbeat-config
data:
  journalbeat.yaml: |
    ---
    journalbeat.inputs:
    - paths: ["/var/log/journal"]
      seek: cursor
    
    processors:
    - add_cloud_metadata: ~
    - add_kubernetes_metadata:
        in_cluster: true
        default_indexers.enabled: false
        default_matchers.enabled: false
        indexers:
          - container:
        matchers:
          - fields:
              lookup_fields: ["container.id"]        
    
    output.elasticsearch:
      hosts: ["elasticsearch:9200"]
