apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: journalbeat
  namespace: monitoring
  labels:
    app: journalbeat
spec:
  selector:
    matchLabels:
      app: journalbeat
  template:
    metadata:
      labels:
        app: journalbeat
      annotations:
       seccomp.security.alpha.kubernetes.io/pod: docker/default
    spec:
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 0
      containers:
      - name: journalbeat
        image: docker.elastic.co/beats/journalbeat:7.1.1
        resources:
          requests:
            cpu: 50m
            memory: 250Mi
          limits:
            cpu: 50m
            memory: 250Mi
        env:
          - name: output.elasticsearch.hosts
            value: '["elasticsearch:9200"]'
        volumeMounts:
        - name: varlog
          mountPath: '/var/log/journal'
        - name: runlog
          mountPath: '/run/systemd'
        - name: machineid
          mountPath: '/etc/machine-id'
        - name: hostname
          mountPath: '/etc/hostname'
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: '/var/log/journal'
      - name: runlog
        hostPath:
          path: '/run/systemd'
      - name: machineid
        hostPath:
          path: '/etc/machine-id'
      - name: hostname
        hostPath:
          path: '/etc/hostname'
