apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    appname: demo
  name: demo-app-2
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      appname: demo
  template:
    metadata:
      labels:
        appname: demo
        appversion: "0.2"
    spec:
      containers:
      - image: docker.io/ehazlett/docker-demo
        name: demo-app
        env: 
        - name: VERSION
          value: "0.2"
