apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hpaexample
  name: hpa-example
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpaexample
  template:
    metadata:
      labels:
        app: hpaexample
    spec:
      containers:
      - image: k8s.gcr.io/hpa-example
        name: hpa-example
        resources:
          requests:
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: hpa-example
  namespace: default
  labels:
    app: hpaexample
spec:
  ports:
    - port: 80
  selector:
    app: hpaexample
