apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    prometheus.io/path: /api/v1/metrics/prometheus
    prometheus.io/port: "2020"
    prometheus.io/scrape: "true"
  labels:
    app: fluent-bit
  name: fluent-bit