apiVersion: v1
kind: Service
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  annotations:
  labels:
    app: istio-ingressgateway
    istio: ingressgateway
spec:
  type: NodePort
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  ports:
    -
      name: http2
      nodePort: 33000
      port: 80
      targetPort: 80
    -
      name: https
      nodePort: 33001
      port: 443
    -
      name: tcp
      nodePort: 33002
      port: 31400
    -
      name: https-prometheus
      port: 15030
      targetPort: 15030
    -
      name: tls
      port: 15443
      targetPort: 15443
    -
      name: status-port
      port: 15020
      targetPort: 15020
---
apiVersion: v1
kind: Service
metadata:
  name: istio-pilot
  namespace: istio-system
  labels:
    app: pilot
    istio: pilot
spec:
  ports:
  - port: 15010
    name: grpc-xds # direct
  - port: 15011
    name: https-xds # mTLS
  - port: 8080
    name: http-legacy-discovery # direct
  - port: 15014
    name: http-monitoring
  selector:
    istio: pilot
