apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: curator2
  namespace: monitoring
spec:
  schedule: 1 0 * * *
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: dtrcreds
          containers:
          - name: curator
            image: dtr.olly.dtcntr.net/admin/curator:5.7.6
            args:
            - --config
            - /etc/config/config.yml
            - /etc/config/action_file.yml
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: curator2-config
          restartPolicy: OnFailure
